### ISSUE TITLE
Strange result in While section

### ISSUE THREAD

**Issue by Victoria-Hodder** [PyLadiesBerlin/python-beginners-workshop#21]
I have found a small bug in the solution to the While loop section.

Using the current code:
```
print()
name = input("What is your name? ")
print(f"Welcome to the dungeon, {name}!")

door = 0
while door not in ('1', '2'):
    wrong_input("1, 2")
    print("Do you go through door 1 or door 2?")
    door = input("> ")
```

Returns this in the terminal:
![Screenshot from 2020-09-09 17-01-20](https://user-images.githubusercontent.com/46939019/92616209-3d0a1380-f2be-11ea-8457-9631f183c146.png)

Which works (technically!) but does not seem user friendly. Is there a way to enter your name and then go to the while loop which checks if you enter a valid input for choosing a door?

**Comment by mei-li** [comment]
Good catch. 
Yes it is possible to have the message being shown only after the the user inputs a door number. I can think of 2 possibilities or repeating the questions and assignment for the door before the loop which is not so nice as we would repeat the same code.
Or we would need a way to know if it is the first iteration and skip the call to `wrong_input`. Do you think there is a way to know if it is the first iteration by checking the value of some variable?

**Comment by Victoria-Hodder** [comment]
Do you mean the first iteration of the `door` variable?

**Comment by mei-li** [comment]
I refer to iteration as a repetition of the code in the while loop. In the first repetition (aka iteration) we want to avoid executing `wrong_input("1, 2")`. To do this we need an `if` . 
As you say by checking the value of the `door` variable we can know if we are in the first iteration. How will the if would look like exactly? 

```print()
name = input("What is your name? ")
print(f"Welcome to the dungeon, {name}!")

door = 0
while door not in ('1', '2'):
    if XXXXXX:
        wrong_input("1, 2")
    print("Do you go through door 1 or door 2?")
    door = input("> ")
```

**Comment by Victoria-Hodder** [comment]
I thought maybe you could write:

```
while door not in ('1', '2'):
    if door != '1' and door !='2':
        wrong_input("1, 2")
    print("Do you go through door 1 or door 2?")
    door = input("> ")
```

Because if the user does not input 1 or 2 it needs to execute the `wrong_input` function.

This is running with the same output as above. So I did not break it... and I did not fix it either! I'm also not sure if this is checking if it is the first iteration or not. And I'm also wondering if it is even necessary to check if the user doesn't input 1 or 2 in the `if` statement because it seems the `while` loop is already doing this.

Is there another way I can look at this? I will think more about how you can check if something is a first iteration with the if statement.

**Comment by mei-li** [comment]
Yes the check if `door != '1' and door != '2'` id actually performed in the
`wrong_input`.
I think here it will help to try to capture the variable value in each line
of code.
Actually I found the tool I was talking about that can help visualize the
values and the execution of the program. Check it here
http://www.pythontutor.com/visualize.html#mode=edit

It has also some examples

Victoria Hodder <notifications@github.com> schrieb am Sa., 12. Sep. 2020,
10:52 vorm.:

**Comment by Victoria-Hodder** [comment]
does the `name` variable need to be considered in the `if` statement?

Thank you for the tool! It's really helping me understand nested while loops!

**Comment by Victoria-Hodder** [comment]
I have an idea. I thought, maybe if the name has already been inputted, the program only has to worry about the input for the door variable...

```
while door not in ('1', '2'):
    if name == False:                 # I also tried with "True"
        wrong_input("1, 2")
    print("Do you go through door 1 or door 2?")
    door = input("> ")
```

This avoids the strange output from before. BUT if I put in a wrong input (e.g. 3 or 4 etc), it just asks again and again "Do you go through door 1 or door 2?" - it does not execute `wrong_input()`

![Screenshot from 2020-09-14 10-38-59](https://user-images.githubusercontent.com/46939019/93063496-a4391680-f676-11ea-8a6d-6bfe81868b22.png)

**Comment by Victoria-Hodder** [comment]
@mei-li  Could you please explain what you mean by "capture the variable value in each line of code"?

**Comment by Victoria-Hodder** [comment]
This is the tutorial I was following for while loops:
https://realpython.com/python-while-loop/
