### ISSUE TITLE
Links to short exercises in Readmes broken

### ISSUE THREAD

**Issue by ellenkoenig** [PyLadiesBerlin/python-beginners-workshop#5]
Hey, I tried to take a look at the "Short exercises", but I find it really difficult to navigate the repo. Both the links to the "short exercises" from the main readme and the links within the readme in the "short exercises" folder are broken. Would be good to have these fixed before the attendees get stuck on the same issue.

**Comment by mei-li** [comment]
fixed by https://github.com/PyLadiesBerlin/python-beginners-workshop/pull/6
